dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/cli/recipes/grr_artifact_hosts.py, dftimewolf/cli/recipes/grr_hunt_artifacts.py, dftimewolf/cli/recipes/grr_hunt_file.py, dftimewolf/cli/recipes/grr_huntresults_plaso_timesketch.py, dftimewolf/cli/recipes/local_plaso.py, dftimewolf/config.py, dftimewolf/lib/collectors/grr.py, dftimewolf/lib/utils.py, requirements.txt, tests/test_dftimewolf.py
The GRR lib that had disappeared was restored and adapted to work with the new dfTimewolf core:
* **GRRHuntArtifactCollector** - starts Artifact collection Hunt
* **GRRHuntFileCollector** - starts File collection Hunt
* **GRRHuntDownloader** - downloads the results of a Hunt to the local filesystem
* **GRRArtifactCollector** - starts an ArtifactCollection flow and downloads results to the local filesystem
* **GRRFileCollector** - starts a FileCollection flow and downloads results to the local filesystem
* **GRRFlowCollector** - downloads the results of a flow to the local filesystem
Additionally some changes were made:
* Some yapf formatting
* CLI arguments take precedence over those in the config file
* Two new tests
* Exporters are skipped if none are specified in the recipes (like the …
=> GRR recipes

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/cli/recipes/timesketch_upload.py
Timesketch supports CSV files uploaded as well. The name of the recipe shouls not be limited to plaso files.
=> Make recipe more intuitive and reflect that CSV upload is supported

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/cli/recipes/artifact_grep.py, dftimewolf/cli/recipes/gcp_turbinia.py, dftimewolf/cli/recipes/gcp_turbinia_import.py, dftimewolf/cli/recipes/grr_artifact_hosts.py, dftimewolf/cli/recipes/grr_fetch_files.py, dftimewolf/cli/recipes/grr_flow_download.py, dftimewolf/cli/recipes/grr_hunt_artifacts.py, dftimewolf/cli/recipes/grr_hunt_file.py, dftimewolf/cli/recipes/grr_huntresults_plaso_timesketch.py, dftimewolf/cli/recipes/local_plaso.py, dftimewolf/cli/recipes/timesketch_upload.py, dftimewolf/lib/collectors/gcloud.py, dftimewolf/lib/exporters/timesketch.py, dftimewolf/lib/module.py, dftimewolf/lib/state.py, tests/cli/recipes.py, tests/lib/collectors/filesystem.py, tests/lib/collectors/grr_base.py, tests/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hunt.py, tests/lib/exporters/local_filesystem.py, tests/lib/exporters/timesketch.py, tests/lib/processors/grepper.py, tests/lib/processors/localplaso.py, tests/lib/processors/turbinia.py
This PR changes the way modules are run in a given recipe.
* All modules are started and setup simultaneously.
* Recipes define which modules should be started as well as which modules act as blockers for other modules to start processing input. Modules can also store and retrieve data to the state object.
This introduces two new features for recipes:
* multiple modules can now re-use data provided by a single module (think threat intelligence used in different modules)
* multiple modules can store information that can later on be re-used (think multiple modules collecting report data that will ultimately be posted to an incident response platform)
=> Better modules feature

dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, tests/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hunt.py
* remove unused method `_get_client_by_id`
* changes to docstrings
* renamed methods to match log2timeline style guide
=> Changes to use log2timeline style guide and removed unused methods #176

dftimewolf/lib/modules/manager.py, dftimewolf/lib/recipes/manager.py, tests/lib/modules/manager.py, tests/lib/recipes/manager.py
This makes it easier to register recipes and modules that have been declared in separate files without knowing their names in advance.
=> Add overwrite boolean

dftimewolf/lib/containers/report.py, dftimewolf/lib/processors/turbinia.py, requirements.txt, tests/lib/containers/report.py
This uses the Turbinia reports instead of the dftimewolf summary, and does a couple other things:
-  Prints out the short version of the report on the command line
- Sets the full report in the Report container for later reporting.
- Adds a `text_format` attribute so we can define this report as markdown. 
- Swaps the version of Turbinia from tomchop's fork to the latest release.
=> Use Turbinia reports and version bump

dftimewolf/lib/containers/containers.py, dftimewolf/lib/state.py, tests/lib/state.py, tests/test_modules/modules.py
This PR introduces StreamingContainers in dfTimewolf.
Modules register StreamingContainersConsumers by passing a callback and an AttributeContainer class to `RegisterStreamingCallback`. Other modules then call `StreamContainer` with the container of their choice, and all callbacks registered for that container type will be called. 
Containers "streamed" this way are not stored and cannot be recovered later on, unless the callback implements an internal mechanism to preserve them.
=> Introduce StreamingContainers

data/recipes/gcp_forensics.json
The image project and image family in the current GCP recipe is inverted, causing the recipe to fail with the following error message:
```
$: dftimewolf gcp_forensics --instance instance_name --analysis_project_name project_name other_project_name incident_id
$: googleapiclient.errors.HttpError: <HttpError 404 when requesting https://compute.googleapis.com/compute/v1/projects/ubuntu-1804-lts/global/images/family/ubuntu-os-cloud?alt=json returned "The resource 'projects/ubuntu-1804-lts' was not found">
```
See https://cloud.google.com/compute/docs/images
=> Fix GCP recipe.

docs/developers-guide.md
Since dfTimewolf now uses CamelCase, this can be removed.
=> Fix developers guide method case

dftimewolf/lib/processors/turbinia.py, tests/lib/processors/turbinia.py
This should speed up the runs a bit.   In the next release of Turbinia we should be able to handle this with a recipe.  Also, the flags for this are getting renamed in the next release (https://github.com/google/turbinia/pull/554/), but I'll push another change here before that gets released.
=> Disable expensive Turbinia jobs by default

dftimewolf/cli/dftimewolf_recipes.py
dfTimewolf output will not be colorized if the environment variable `DFTIMEWOLF_NO_RAINBOW` is set.
=> Add option to remove colorization

config/linux/jenkins_dftimewolf_install.sh
This fixes some broken e2e tests
=> use the relase docker image (stable)

config/linux/jenkins_dftimewolf_install.sh
Add required env variable to tell Docker what version of ES to run.
=> Set ES version for Timesketch e2e tests

dftimewolf/lib/collectors/gcloud.py, tests/lib/collectors/gcloud.py
At some point in time, `instance_name` and `zone` were flipped in libcloudofrensics, making this brittle as `None` was being passed as the zone name. This made that disks could be created in other zones and failed to attach to the original analysis VM.
=> fix: CreateDisk call passing the proper parameters

dftimewolf/lib/collectors/aws.py, dftimewolf/lib/collectors/filesystem.py, dftimewolf/lib/collectors/gcloud.py, dftimewolf/lib/collectors/gcp_logging.py, dftimewolf/lib/collectors/grr_base.py, dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, dftimewolf/lib/enhancers/timesketch.py, dftimewolf/lib/exporters/gce_disk_export.py, dftimewolf/lib/exporters/local_filesystem.py, dftimewolf/lib/exporters/scp_ex.py, dftimewolf/lib/exporters/timesketch.py, dftimewolf/lib/module.py, dftimewolf/lib/modules/manager.py, dftimewolf/lib/processors/gcp_logging_timesketch.py, dftimewolf/lib/processors/grepper.py, dftimewolf/lib/processors/localplaso.py, dftimewolf/lib/processors/turbinia.py, dftimewolf/lib/state.py, tests/lib/state.py, tests/test_modules/modules.py, tests/test_modules/test_recipe.py
Modules can now be identified by their `runtime_name` instead of their class names. This allows to disambiguate modules when there is more than one module of the same type in a recipe.
I didn't find a better variable name than `runtime_name`. WDYT?
=> Introduce runtime names for modules

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/module.py, dftimewolf/lib/state.py, tests/lib/state.py, tests/test_modules/modules.py
These are called at the end of the *recipe* (after calling all the module's `Process()` functions), to clean-up any artifacts left behind by preflights
=> Introduces Preflight CleanUp functions

dftimewolf/lib/collectors/gcloud.py, tests/lib/collectors/gcloud.py
Pretty self explanatory I reckon. By checking that the target is valid before launching the VM, we don't launch the VM on a target error.
=> Check target instance exists before launching analysis VM

docs/user-manual.md
I needed to look back at an months old chat with @tomchop to find out how to deactivate
=> Mention DFTIMEWOLF_NO_RAINBOW in user manual

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/errors.py, dftimewolf/lib/state.py, tests/lib/state.py
Raise `CriticalError` instead of just calling exit()
=> Better critical error handling

data/recipes/grr_artifact_grep.json, data/recipes/grr_artifact_ts.json, data/recipes/grr_files_collect.json, data/recipes/grr_flow_collect.json, data/recipes/grr_timeline_ts.json, dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/containers/containers.py, tests/lib/collectors/grr_hosts.py
This PR changes the way GRR modules deal with hosts. Instead of strings, they now manipulate `containers.Host` attribute containers. This makes it possible for other modules (e.g. "user2host") to generate containers for the GRR modules to work on.
=> Hosts in GRR modules are attribute containers instead of strings

data/recipes/gcp_logging_gce_instance_ts.json
Instance IDs now require going through `labels`
https://cloud.google.com/logging/docs/view/advanced-queries#right-log-entries
=> Adjust logging query

dftimewolf/lib/exporters/timesketch.py
The Error message references sketch_id (str) instead of the correct self.sketch_id (int). Because of that the following error is thrown when reaching the original line 89:
ValueError: Unknown format code 'd' for object of type 'str'
The fix uses self.sketch_id, which has already been converted to an int in line 71.
=> Fixed sketch-id error message

setup.py
Error #381 still persists when trying to install.
In line 22 of setup.py there seems to be a logic bug when skipping lines in the requirements file - it does the opposite to what was intended.
=> Fix bug in removing lines that start with # and '-i'

dftimewolf/lib/processors/turbinia_gcp.py, tests/lib/processors/turbinia_gcp.py
This is to match the recipe structure in the new release of Turbinia.
=> Move Turbinia recipe variables

dftimewolf/lib/containers/containers.py
Allows for users of the DataFrame container to specify the source of data, which can then be used by modules processing this container.
=> Add source attribute to the DataFrame container definition

dftimewolf/lib/logging_utils.py, dftimewolf/lib/module.py, tests/lib/state.py, tests/test_modules/thread_aware_modules.py
Adds the thread name to log messages for logging within a threadawaremodule's Process method. Allows for better identification of log messages when multiple threads are running. 
Sample from unittests:
```
<snip>
[2021-11-08 23:19:54,699] [dftimewolf          ] INFO     Module ContainerGeneratorModule finished execution
[2021-11-08 23:19:54,699] [dftimewolf          ] INFO     Running module: ThreadAwareConsumerModule
[2021-11-08 23:19:54,699] [ThreadAwareConsumerModule] INFO     ThreadAwareConsumerModule Static Pre Process
[2021-11-08 23:19:54,699] [dftimewolf          ] INFO     Running 3 threads, max 2 simultaneous for module ThreadAwareConsumerModule
[2021-11-08 23:19:54,700] [ThreadAwareConsumerModule] INFO     [ThreadPoolExecutor-1_0] ThreadAwareConsumerModule Process!
[2021-11-08 …
```
=> Add thread name to logging for thread aware modules

.github/workflows/docs.yaml
`mkdocs gh-deploy --force` will build the documentation in the repo root (/) on the `gh-pages` branch.
=> Add github action to deploy docs

dftimewolf/lib/collectors/aws_snapshot_s3_copy.py, dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/exporters/gce_disk_from_image.py, dftimewolf/lib/exporters/gcs_to_gce_image.py, dftimewolf/lib/exporters/s3_to_gcs.py, dftimewolf/lib/exporters/timesketch.py, dftimewolf/lib/module.py, dftimewolf/lib/processors/turbinia_gcp_tam.py, dftimewolf/lib/state.py, tests/lib/state.py, tests/test_modules/thread_aware_modules.py
These two methods don't provide any value, and so just create unneeded empty method stubs in TAM implementations.
Closes #500.
=> Removed Pre&PostSetup from ThreadAwareModule

dftimewolf/metawolf/metawolf.py
=> Fix colored prompt on readline-enabled terminals

dftimewolf/metawolf/metawolf.py, dftimewolf/metawolf/output.py
- Fix some help texts which displayed the old syntax (e.g. `show output` vs. `show -o[utput]`)
- Display the list of recipe's arguments that were reset to their default value when using the `reload` command
- Escape correctly color codes when prompting the user for inputs
- Allow users to bail early when using `set -a` with `ctrl+d` (e.g. if the recipe has many optional arguments)
- Fix process status when non-dftimewolf errors occur (esp. between restarts of metawolf)
- Remove the `help` command override, because this messes up with cmd2's capabilities (e.g. prevents getting help for a specific command)
- Add a new `send` command, to communicate with the `STDIN` of running processes. This is particularly useful when running recipes that require user inputs during their lifecycle …
=> Fixes and enhancements for metawolf

tests/e2e/gcp_disk_forensics.py
Stage 3 of #524 - End to End tests. 
Supporting methods `ReadProjectInfo` and `CleanUp` copied directly from the source `gcloud_e2e.py`. Otherwise, this version differs from the original in that it loads a test recipe and executes it before checkout output. (The original tested the single module with no recipe.)
=> New e2e test for new GCE disk forensics modules

data/recipes/gcp_forensics_new.json
Adding in a temp recipe for the new GCE forensics modules. This recipe will exist along side the original while updates are made to E2E testing pipelines for easier rolling back of said tests if something breaks. Eventually, this recipe will replace `gcp_forensics.json`
=> Added in recipe for new GCE forensics modules

data/recipes/workspace_meet_ts.json, dftimewolf/lib/collectors/workspace_audit.py, docs/recipe-list.md
Added a filter that removes the '-' delimiters form the meeting_id when used with the workspace_meet_ts recipe. Additionally I added the info to use the meeting_id without delimiters to the documentations and help as well.
=> Filter for meeting_id delimiter

dftimewolf/lib/collectors/gce_disk_copy.py, dftimewolf/lib/containers/containers.py, dftimewolf/lib/state.py, tests/lib/processors/test_data/turbinia.conf, tests/lib/state.py, tests/test_modules/thread_aware_modules.py
Create supporting method in DFTimewolfState to dedupe containers of a certain type, and use that in GCEDiskCopy.
This ensures that if multiple GCEDiskCopy modules are run in a single recipe, they don't duplicate their list in PreProcess.
=> Dedupe containers in GCEDiskCopy module

dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/exporters/scp_ex.py, tests/lib/collectors/grr_hosts.py
Updated GRRFlowCollector to raise an error when no flows are found. This can occur if the user specifies a child flow rather than a parent flow, which is no longer supported.
In SetUp, each flow that is not found will be noted as a warning:
```
[2022-03-02 02:51:37,686] [GRRFlowCollector    ] WARNING  The following flows were not found: F:23456, F:34567
[2022-03-02 02:51:37,687] [GRRFlowCollector    ] WARNING  Did you specify a child flow instead of a parent?
```
In PreProcess, if no flows are found at all, an error is raised. SetUp doesn't error in the event the containers are coming from a previous module.
```
[2022-03-02 02:55:50,353] [GRRFlowCollector    ] CRITICAL No flows found for collection.
```
In Process, if a flow has no data collected:
```
[2022-03-02 03:08:47,585] …
```
=> GRRFlowCollector - Error handling improvements

dftimewolf/lib/processors/turbinia_gcp.py, tests/lib/processors/turbinia_gcp.py
Currently the TurbiniaGCPProcessor module doesn't consider the project in the GCEDiskEvidence container, meaning it may attempt to process disks in other projects. This change corrects that behaviour.
=> TurbiniaGCP - Ignore disks in other projects

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/module.py, tests/lib/collectors/grr_hosts.py
This removes duplicate log entries when some modules are used:
Before:
```
[2022-03-07 03:37:45,074] [dftimewolf          ] INFO     Running module: LocalFilesystemCopy
[2022-03-07 03:37:45,074] [LocalFilesystemCopy ] INFO     <path> -> /tmp/dftimewolf_local_fs0t8tq4ta
2022-03-07 03:37:45 [INFO] <path> -> /tmp/dftimewolf_local_fs0t8tq4ta
[2022-03-07 03:37:45,079] [LocalFilesystemCopy ] SUCCESS  <path> was compressed into /tmp/dftimewolf_local_fs0t8tq4ta/<output>.tgz
2022-03-07 03:37:45 [SUCCESS] <path> was compressed into /tmp/dftimewolf_local_fs0t8tq4ta/<output>.tgz
[2022-03-07 03:37:45,079] [dftimewolf          ] INFO     Module LocalFilesystemCopy finished execution
```
After:
```
[2022-03-07 03:42:41,743] [dftimewolf          ] INFO     Running module: LocalFilesystemCopy
[2022-03-07 …
```
=> Remove log propagation from child to root

dftimewolf/lib/processors/turbinia_base.py
This is a bugfix. The Turbinia evidence object was not properly set in the call to Turbinia client's create_request() method.
=> Bug fix: set evidence object when calling Turbinia create_request()

dftimewolf/lib/collectors/gce_disk_copy.py, dftimewolf/lib/containers/containers.py, dftimewolf/lib/exporters/gce_disk_from_image.py, dftimewolf/lib/processors/gce_forensics_vm.py, dftimewolf/lib/processors/turbinia_gcp.py, tests/e2e/aws_disk_forensics.py, tests/e2e/gcp_disk_forensics.py, tests/lib/collectors/gce_disk_copy.py, tests/lib/exporters/gce_disk_from_image.py, tests/lib/processors/gce_forensics_vm.py, tests/lib/processors/turbinia_gcp.py
The two containers represent the same object, and so removed GCEDiskEvidence and replaced all usages of it with GCEDisk.
=> Consolidate GCEDisk and GCEDiskEvidence containers

data/recipes/gcp_turbinia_ts.json, dftimewolf/lib/processors/turbinia_base.py
Create a TurbiniaProcess method specific turbiniaclient object in turbinia base. Should alleviate thread safety issues in having a single shared turbiniaclient object.
Fixes #600
=> Fix thread safety issue in turbinia modules

dftimewolf/lib/processors/gce_forensics_vm.py, tests/lib/processors/gce_forensics_vm.py
If an evidence disk is attached too close to instance launch, and the evidence disk is a boot disk from the copied VM, the VM can fail to pick the correct disk to launch from, since both disks are equally correct, as far as the VM is concerned. Adding a delay to attaching evidence disks will ensure that the correct disk is booted from.
=> Added delay between GCE launch and evidence disk attachment

dftimewolf/lib/processors/gce_forensics_vm.py, tests/e2e/gcp_disk_forensics.py
Currently, if the GCEForensicsVM fails to attach a disk because it is already attached to another instance, there is an uncaught `RuntimeError` thrown. This can happen if evidence disks are copied from the same project where the forensics VM is created (as seen in the E2E test.) This change checks if that is the case, and prints a warning, but continues.
Fixes #609
=> Don't fail the GCEForensicsVM module if a evidence disk can't be attached.

dftimewolf/lib/collectors/grr_base.py, dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, tests/lib/collectors/grr_base.py
Currently GRR MPA urls are sent to the logger. This PR ensures that the url is also sent to `module.PublishMessage`, so in curses mode the operator still is able to retrieve it.
=> Made Grr approval urls visible in curses mode

dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/containers/containers.py
If multiple grr host modules are set to run, they each try to add the host in SetUp to the container store, which results in duplicate flows being initiated. This rectifies that by deduping the containers.
=> Add in container deduping to grr host modules

dftimewolf/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hosts.py
By [default](https://github.com/google/grr/blob/master/grr/proto/grr_response_proto/flows.proto#L1852) the PathType for the GRR File Finder flow uses `OS`. When TSK is enabled via the command line this option is passed into the GRR client's flow arguments.
=> Fix GRRFileCollector to use TSK API input for GRR

dftimewolf/cli/dftimewolf_recipes.py
Currently, when passing `-h` to a recipe, argparse sends the output to stdout. In the context of the curses UI we'd prefer it be sent to stderr, so it gets captured and displayed to the user.
=> Redirect stdout to stderr for argparse

dftimewolf/lib/processors/turbinia_artifact.py, dftimewolf/lib/processors/turbinia_base.py, dftimewolf/lib/processors/turbinia_gcp.py
Surface the turbinia request ID to the user via PublishMessage.
Required a small amount of refactoring - moving `TurbiniaStart` and `TurbiniaWait` out of `TurbiniaProcess` into the child classes (and removing `TurbiniaProcess` as it's not used any more as a result.)
=> Surface the turbinia request ID to the user via PublishMessage

dftimewolf/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hosts.py
With this modification to the `_DownloadFiles()` function, the grr collector now checks if a given GRR flow is a TimelineFlow and then proceeds to download the resulting TimelineBody file instead of the empty FilesArchive.  This will allow dftimewolf recipes to also process timeline results from GRR that have been collected earlier e.g. via the GRR interface.
=> Fix for downloading grr timeline flow results

dftimewolf/cli/curses_display_manager.py, dftimewolf/lib/collectors/bigquery.py, tests/cli/curses_display_manager.py
In curses mode, if the terminal is too short (read: has too few rows) the cursor moves off the screen, and an uncaught exception is thrown. This PR catches that exception and advises the user they may wish to make the terminal larger, and keeps running the recipe.
=> Handle curses error when window is too short

dftimewolf/lib/containers/containers.py
This PR adds ```__eq__``` and ```__str__``` methods to the OsqueryResults container.
=> Add __eq__ and __str__ methods to OsqueryResults container

dftimewolf/lib/containers/interface.py, dftimewolf/lib/state.py, tests/lib/containers/interface.py, tests/lib/state.py
Added ability to set metadata on a container, and then use that metadata to filter retrieval of containers via state.GetContainer()
=> GetContainers() filter on metadata

dftimewolf/lib/exporters/local_filesystem.py, tests/lib/exporters/local_filesystem.py
Enable `dir_exist_ok` in LocalFilesystemCopy so that output files do not have a random string named directory to ensure uniqueness.
Now that support for 3.7 has been dropped (#566), we can revert #471 (the `dir_exists_ok` option was introduced in 3.8.)
=> Enable dir_exists_ok in LocalFilesystemCopy

dftimewolf/lib/containers/containers.py
Added metadata attribute to the Dataframe container. The attribute is optional and I am intending to use this metadata in the future.
=> Add optional metadata attribute to Dataframe container

dftimewolf/lib/collectors/workspace_audit.py
This PR updates the workspace audit module to use the localhost http server authentication flow for Google OAuth2. The original OOB method provided by ```run_console()``` has been deprecated.
=> Migrate deprecated OOB flow to localhost http server

dftimewolf/lib/collectors/aws.py, dftimewolf/lib/collectors/aws_logging.py, dftimewolf/lib/collectors/aws_snapshot_s3_copy.py, dftimewolf/lib/collectors/aws_volume_snapshot.py, dftimewolf/lib/collectors/azure.py, dftimewolf/lib/collectors/azure_logging.py, dftimewolf/lib/collectors/bigquery.py, dftimewolf/lib/collectors/filesystem.py, dftimewolf/lib/collectors/gcp_logging.py, dftimewolf/lib/collectors/grr_base.py, dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, dftimewolf/lib/collectors/workspace_audit.py
Ref styleguide change https://github.com/log2timeline/l2tdocs/pull/55
=> Added f-strings to collector modules

dftimewolf/cli/dftimewolf_recipes.py
Currently in curses mode, the help text is sent to stderr to be collected and displayed by the CDMStringIOWrapper. This change doesn't use curses mode when the help option/s are provided, and moves the help text to stdout.
=> Output help text on stdout, without curses

docs/developers-guide.md
The section in the documentation describing how to create recipes contained two links that didn't work. These habe been fixed. However, recipe `local_plaso` mentioned in the text no longer exists. It has been replaced by the recipe `plaso_ts` as an example.
=> Fix links to recipes in doc

.github/workflows/install.yml, docs/developers-guide.md, docs/getting-started.md, pyproject.toml
* Remove references to `pip`. This was confusing for users (rightly so, as the documentation mentions this is the way to install dftimewolf). We now exclusively use `poetry` to install this package.
* Add a `poetry.script` reference to `pyproject.toml` to ensure that the `dftimewolf` script is available in poetry's virtualenv.
=> Remove references to `pip`

dftimewolf/cli/dftimewolf_recipes.py
Continue in non-curses mode if there is no tty. 
Fixes #616
=> Disable curses if there is no tty

data/recipes/gcp_logging_cloudaudit_ts.json, data/recipes/gcp_logging_cloudsql_ts.json, data/recipes/gcp_logging_collect.json, data/recipes/gcp_logging_gce_instance_ts.json, data/recipes/gcp_logging_gce_ts.json, dftimewolf/lib/collectors/gcp_logging.py, docs/recipe-list.md
This PR adds two optional arguments to the gcp_logging_collect recipe: backoff and delay. These are introduced to help manage GCP's logging api limits, which I have regularly exceeded when using dftimewolf.
Both are disabled by default, so should not impact existing dftimewolf workflows.
Backoff is a boolean value, which if True, will retry log collection if the GCP logging API quota is exceeded. Due to the way the logging API handles subsequent requests after exceeding an the API limit (https://github.com/log2timeline/dftimewolf/issues/679), a new cloud logging client must be created for the re-try. This means the collection must start again. If no delay was configured, the collection will be retried with a delay of 1s between each request. If a delay was configured, the collection will …
=> Feature backoff and delay

dftimewolf/cli/curses_display_manager.py, tests/cli/curses_display_manager.py
This PR corrects the redraw behaviour when SIGWINCH is raised when curses mode is in use.
=> Fix redraw in curses mode on SIGWINCH

data/recipes/aws_disk_to_gcp.json, data/recipes/aws_turbinia_ts.json, tests/e2e/aws_disk_forensics.py, tests/e2e/gcp_disk_forensics.py
Add args validation to E2E tests
Also, correction to aws subnets - they're AWS subnet IDs, not actual network addresses with masks.
=> Add args validation to E2E tests

dftimewolf/lib/containers/containers.py, dftimewolf/lib/exporters/local_filesystem.py, tests/lib/exporters/local_filesystem.py
This will prevent errors when outputting to a directory you can write to, but not alter (such as `/tmp`)
=> Add source basename to destination dir in LocalFilesystemCopy

data/recipes/upload_turbinia.json, dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/args_validator.py, tests/lib/args_validator.py
Changes argument validators to return a `tuple[bool, str]` rather than nothing, or raise an exception. This is better suited for cases of overlap, such as between fqdns, flat hostnames, urls and grr ids.
=> Argument Validator updates

config/linux/jenkins_dftimewolf_install.sh
We switched to ubuntu 22.04 on the CI platform, which supports python3 by default (and is able to install plaso-tools)
=> Update jenkins script

dftimewolf/lib/containers/interface.py, dftimewolf/lib/module.py, dftimewolf/lib/state.py
Moving the source container info into container metadata means it can be filtered on.
=> Move container.src_module_name into metdata

dftimewolf/cli/dftimewolf_recipes.py, tests/cli/main_tool.py
Added the ability to pass an argument `--dry_run` that causes the arguments to be parsed and validated, but exists before any module execution. 
The flag needs to be between the executable and the recipe on the command line, otherwise it is treated as a recipe argument, eg 
```
poetry run dftimewolf --dry_run upload_ts <etc>
```
=> Added dry_run flag

dftimewolf/lib/preflights/ssh_multiplexer.py, tests/lib/preflights/ssh_multiplexer.py
This PR solves a problem when running to parallell dftimewolf commands, and the first one finishes before the second one, and therefore cleans up the SSH control channel that the second one would've used to download things.
=> Make every SSH multiplexing connection unique

dftimewolf/cli/curses_display_manager.py, dftimewolf/lib/module.py, dftimewolf/lib/state.py, tests/cli/curses_display_manager.py
Added an ability for modules to report progress updates. Currently, curses mode is supported, presented to the user as a percentage next to the module name for a single threaded module, and next to the thread for a threaded module.
```
Recipe name
Preflights:
1st Preflight: Completed
2nd Preflight: Completed
Modules:
1st Module: Completed
2nd Module: Running 40.0%
3rd Module: Processing - 1 of 5 containers completed
thread_3_0: Running 20.0% (container_3_4)
```
=> Added module progress reporting

dftimewolf/lib/exporters/scp_ex.py, dftimewolf/lib/preflights/ssh_multiplexer.py, docker/dftimewolf-dev/Dockerfile, tests/lib/exporters/scp_ex.py
If `destination` isn't specified, use mkdtemp to create a temporary directory
=> Use mkdtemp in scp_ex

dftimewolf/lib/logging_utils.py
The custom logging.Formatter.format message breaks the usage of %-based templates while using the wolf logger. Changing to f-string.
=> The custom logging.Formatter.format message breaks the usage of %-based templates while using the wolf logger. Changing to f-string.

dftimewolf/lib/module.py
When dfTimewolf is used as a library, loading modules more than once would registger their handlers again, duplicating logging in stdout.
=> Clear logging handlers on module init.

data/recipes/gcp_disk_export_dd.json
Fixes trailing whitespace in gcp_disk_export_dd.json recipe documentation
=> Fix trailing whitespace in recipe

dftimewolf/lib/processors/turbinia_base.py
This will change it so the browser is not automatically launched by the auth library
=> Disable browser launch for OAuth flow

data/recipes/gcp_logging_ts.json
Adding a recipe `gcp_logging_ts` that collects logging data from GCP based of a user provided custom query and sends it directly to Timesketch.
=> Adding gcp_logging_ts

dftimewolf/cli/dftimewolf_recipes.py
This allows the telemetry object to be loaded with a new configuration after initializing DFTimewolfTool
=> Extract Telemetry from init to its own method

dftimewolf/lib/exporters/timesketch.py
Timesketch has a character limit for sketch names of 255. (Database limitation)
This PR introduces a check for the `incident_id` length and will truncate it so that the final `sketch_name` will be max 255 characters.
Since this logic changes the user provided `incident_id`, it also logs a warning to let the user know about the change.
=> Timesketch exporter: Handle sketch names > 230 characters

dftimewolf/lib/processors/turbinia_base.py
This PR should handle some authentication errors that were previously missed, for example by not checking if the token was still valid before sending a request in TurbiniaStart(). This is rare but can happen if another module takes 8+ hours before passing data along to the Turbinia module, by which time the access token expires.
=> TurbiniaProcessorBase: Refresh credentials and handle additional exception

dftimewolf/lib/exporters/timesketch.py, tests/lib/exporters/timesketch.py
This PR fixes the sketch URL posted to the log by the Timesketch Exporter module.
=> Timesketch Exporter fix logged sketch URL

README.md
The link to the docs in README is broken.  Updating the link to point to dfTimewolf docs and adjusting related phrasing accordingly.
=> updated docs link in README

config/e2e/jenkins_dftimewolf_install.sh
The Jenkins runners have been updated, and now come with py3.12 by default.
=> Remove py3.11 installation from jenkins set up script

data/recipes/workspace_user_device_ts.json
Adds a new workspace mobile/device recipe to pull these logs and put them into Timesketch to help with correlation with other workspace logs.
Recreated from https://github.com/log2timeline/dftimewolf/pull/866 as seemed to have pulled all the new commits as part of the PR
=> Add workspace device logs recipe

config/e2e/e2e_grr_artifact_hosts.sh, config/e2e/jenkins_dftimewolf_install.sh, docker/dev/README.md, docker/dftimewolf-release/README.md, docs/developers-guide.md
Upgrades the docker instructions to use the modern `docker compose` instead of legacy `docker-compose`
=> Upgrade jenkins script

dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, tests/lib/collectors/grr_hosts.py
Fixes #755 
In addition, GRR "chunks" osquery results [0] which when being retrieved, results in multiple OsqueryResult payloads and subsequently multiple dataframes/CSVs.  This PR changes the behaviour in GRROsqueryCollector and GRRHuntOsqueryDownloader to merge results into a single dataframe (as with the new method in GrrFlowCollector)
[0] https://github.com/google/grr/blob/master/grr/client/grr_response_client/client_actions/osquery.py#L81
=> Add support for downloading osquery results with GrrFlowCollector

dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py
* Fixes `pathspec` proto field name (from `path_spec`).  
* Adds client hostname and client ID as additional columns when collecting osquery hunt results
=> Updates to GRR Osquery modules

dftimewolf/lib/processors/gcp_cloud_resource_tree.py
Adding support for additional log types:
* compute.regionInstances
* compute.regionDisks
* compute.regionInstanceTemplates
Checking for cases where a response is returned with no '@type'.
=> GCP Resource Tree bug fix

docs/developers-guide.md
Updated developer guided to use run local `poetry` tests.
**Standard**
- `docker compose run --rm -v `pwd`/../../:/app dftw poetry run pytype --config /app/pytype.conf`
- `poetry run pytype --config pytype.conf`
**Docker**
- `docker compose run --rm -v `pwd`/../../:/app dftw poetry run mypy --install-types --cache-dir /tmp/.mypy_cache --non-interactive -p dftimewolf`
- `docker compose run --rm -v `pwd`/../../:/app dftw poetry run mypy --install-types --cache-dir /tmp/.mypy_cache --non-interactive -p dftimewolf`
=> Updated developer guide to use mypy and pytype tests

data/recipes/gce_disk_export.json
The help text broke the help text output by having an embedded format string.
=> Small update to recipe help text

dftimewolf/lib/processors/gcp_logging_timesketch.py, tests/lib/processors/gcp_logging_timesketch.py
Changes
- Added attribute definition in `GCPLoggingTimesketch`
- Changed `dcsa_email: str` to `dcsa_emails: list[str]`
- Added `status_reasons: list[str]`
- Added unit test `testServiceAccountCreateFailed`
=> Added attributes types and new attribute status_reasons

dftimewolf/lib/containers/manager.py, dftimewolf/lib/state.py, tests/lib/containers/manager.py
Re-implement container popping in the new container manager. Modules can only pop containers that they stored, otherwise popping is ignored. 
This is to allow modules to use and remove containers as their own temporary storage, as some modules do, which breaks compatibility with the new container manager.
=> Reimplement container popping in new container manager.

dftimewolf/lib/processors/openrelik.py, tests/lib/processors/openrelik.py
Temporarily make module errors non critical while the module is tested out.
=> Make OpenRelik module errors non critical for now

dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/processors/gcp_logging_timesketch.py, tests/lib/collectors/test_data/mock_grr_hosts.py
This PR resolves the `datetime` deprecation warnings which you can see in the [CI logs](https://github.com/log2timeline/dftimewolf/actions/runs/14746769827/job/41395497052#step:5:296):
```python
/home/runner/work/dftimewolf/dftimewolf/dftimewolf/lib/collectors/grr_hosts.py:189: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
/home/runner/work/dftimewolf/dftimewolf/dftimewolf/lib/collectors/grr_hosts.py:194: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC). …
```
=> Refactor datetime calls to remove deprecation warnings

tests/lib/exporters/df_to_filesystem.py
Tests should write to /tmp/, not the working directory.
=> DF-export-to-file test fix

dftimewolf/lib/containers/manager.py, tests/lib/containers/manager.py
This allows the module to use container storage as a personal cache
=> Allow a module to store containers only itself can retrieve

dftimewolf/lib/collectors/gce_disk_copy.py, dftimewolf/lib/exporters/gce_disk_export.py, tests/lib/exporters/gce_disk_export.py
* Plumb instance and disk names through two modules, `GoogleCloudDiskExport` and `GCEDiskCopy`
* Refactor `GoogleCloudDiskExport` to process disks from previous modules
=> Updates to GCE Disk copying
