log2timeline/dftimewolf

dftimewolf/__init__.py, dftimewolf/lib/__init__.py, dftimewolf/lib/collectors.py, dftimewolf/lib/processors.py, dftimewolf/lib/timesketch_utils.py, dftimewolf/lib/utils.py, dftimewolf/timewolf_cli.py, dftimewolf/timewolf_collect.py, dftimewolf/timewolf_export.py, dftimewolf/timewolf_process.py
[Code review: 308600043: First draft of timewolf code.](https://codereview.appspot.com/308600043/)
=> 308600043: First draft of timewolf code.

dftimewolf/__init__.py, dftimewolf/lib/__init__.py, dftimewolf/lib/collectors.py, dftimewolf/lib/processors.py, dftimewolf/lib/timesketch_utils.py, dftimewolf/lib/utils.py, dftimewolf/timewolf_cli.py, dftimewolf/timewolf_collect.py, dftimewolf/timewolf_export.py, dftimewolf/timewolf_process.py, requirements.txt, utils/upload.py
[Code review: 311990043: Misc fixes, cleanups, docstring updates.](https://codereview.appspot.com/311990043/)
=> 311990043: Misc fixes, cleanups, docstring updates.

dftimewolf/lib/collectors.py, dftimewolf/lib/processors.py, dftimewolf/lib/timesketch_utils.py, dftimewolf/lib/utils.py, dftimewolf/timewolf_cli.py, dftimewolf/timewolf_collect.py
[Code review: 314900043: Docstrings for collector lib.](https://codereview.appspot.com/314900043/)
=> 314900043: Docstrings for collector lib.

dftimewolf/lib/collectors.py, dftimewolf/lib/processors.py, dftimewolf/timewolf_cli.py, dftimewolf/timewolf_process.py
[Code review: 318960043: Minor runner_args change + support for local plaso installations.](https://codereview.appspot.com/318960043/)
=> 318960043: Minor runner_args change + support for local plaso installations.

dftimewolf/lib/collectors.py, dftimewolf/lib/utils.py, dftimewolf/timewolf_cli.py
[Code review: 316990043: Fix some docstrings.](https://codereview.appspot.com/316990043/)
=> 316990043: Fix some docstrings.

dftimewolf/lib/collectors.py, dftimewolf/lib/processors.py, dftimewolf/timewolf_cli.py, dftimewolf/timewolf_collect.py, dftimewolf/timewolf_export.py, dftimewolf/timewolf_process.py
[Code review: 316040043: Fix issue in passing artifact paths to processors.](https://codereview.appspot.com/316040043/)
=> 316040043: Fix issue in passing artifact paths to processors.

.style.yapf, dftimewolf/timewolf_cli.py, dftimewolf/timewolf_collect.py, dftimewolf/timewolf_export.py, dftimewolf/timewolf_process.py, run_tests.py, utils/review.py
[Code review: 325810043: Add Yapf config, reformat with yapf.](https://codereview.appspot.com/325810043/)
=> 325810043: Add Yapf config, reformat with yapf.

readme.md, setup.py
Update setup.py (and readme.md) so installation doesn’t fail (and
dftimewolf works)
=> fix install

dftimewolf/cli/dftimewolf_recipes.py
Softly fail if no config file is specified (displays an error message).
=> Soft fail if config unreadable

dftimewolf/cli/recipes/grr_artifact_hosts.py, dftimewolf/cli/recipes/grr_huntresults_plaso_timesketch.py, dftimewolf/cli/recipes/local_plaso.py, dftimewolf/config.py, dftimewolf/lib/exporters/timesketch.py, dftimewolf/lib/utils.py
Also fixed a bug that happened when a parameter was provided with a default "None" value.
=> Add possibility to provide a --sketch_id argument in timesketch recipes

dftimewolf/cli/recipes/grr_artifact_hosts.py, dftimewolf/lib/collectors/grr.py
Use case: we want default artifacts + BrowserHistory (which is not included by default)
=> Add an optional --extra_artifacts argument

dftimewolf/lib/collectors/grr.py
GRR change the names of the OSX artifacts. This fixes it.
=> New MacOS artifacts

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/config.py
This change takes ~/.dftimewolfrc files into account
=> Change the way arguments are overridden 

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/cli/recipes/grr_artifact_hosts.py, dftimewolf/cli/recipes/grr_flow_download.py, dftimewolf/cli/recipes/grr_hunt_artifacts.py, dftimewolf/cli/recipes/grr_hunt_file.py, dftimewolf/cli/recipes/grr_huntresults_plaso_timesketch.py, dftimewolf/cli/recipes/local_plaso.py, dftimewolf/cli/recipes/plaso_file_timesketch.py, dftimewolf/lib/utils.py
dftimewolf now provides better help messages. I'm still using docstrings for now but I will open a separate issue to change this along with `# TODO(tomchop): Add name attributes in module objects`
=> Better help messages! (fixes #54)

requirements.txt
=> Fix beautifulsoup4 package name

dftimewolf/lib/collectors/filesystem.py, dftimewolf/lib/state.py, tests/lib/collectors/filesystem.py
And fix some bugs in the process.
=> Add tests for FilesystemCollector

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/collectors/grr_base.py, dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, dftimewolf/lib/exporters/local_filesystem.py, dftimewolf/lib/exporters/timesketch.py, dftimewolf/lib/processors/localplaso.py, dftimewolf/lib/state.py
Switch to using print function for improved Python 3 compatibility.
=> Switch to using print function for improved Python 3 compatibility.

Pipfile, Pipfile.lock, dftimewolf/cli/recipes/grr_artifact_hosts.py, dftimewolf/cli/recipes/grr_flow_download.py, dftimewolf/cli/recipes/grr_hunt_artifacts.py, dftimewolf/cli/recipes/grr_hunt_file.py, dftimewolf/cli/recipes/grr_huntresults_plaso_timesketch.py, dftimewolf/lib/collectors/grr_base.py, requirements.txt, setup.py, tests/lib/collectors/grr_base.py, tests/lib/collectors/grr_hosts.py
Useful when testing.
Also updated and pinned dependencies for `grr-api-client` since this feature is relatively new.
=> Add verify parameter to GRR modules

.gitignore, dftimewolf/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hosts.py, tests/lib/collectors/test_data/mock_grr_hosts.py
Ready for review. Codefactor warnings can be ignored ("insecure usage of /tmp")
=> Add more tests

dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, tests/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hunt.py, tests/lib/collectors/test_data/mock_grr_hosts.py
Ready for review, codecov issues are about the temp directory.
=> More tests

.travis.yml, config/travis/runtests.sh, tests/lib/processors/turbinia.py
Moved Travis CI LInux builds to Xenial VMs
=> Moved Travis CI LInux builds to Xenial VMs

dftimewolf/lib/module.py
Removed threading from module interface
=> Removed threading from module interface

data/artifact_grep.json, data/gcp_turbinia.json, data/gcp_turbinia_import.json, data/grr_artifact_hosts.json, data/grr_fetch_files.json, data/grr_flow_download.json, data/grr_hunt_artifacts.json, data/grr_hunt_file.json, data/grr_huntresults_plaso_timesketch.json, data/local_plaso.json, data/timesketch_upload.json, dftimewolf/lib/recipes/manager.py, tests/lib/recipes/manager.py
Moved recipes into JSON files #161
=>  Copied recipes into JSON files #161

dftimewolf/lib/collectors/filesystem.py, dftimewolf/lib/collectors/gcloud.py, dftimewolf/lib/collectors/grr_base.py, dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, dftimewolf/lib/collectors/stackdriver.py, dftimewolf/lib/exporters/local_filesystem.py, dftimewolf/lib/exporters/timesketch.py, dftimewolf/lib/module.py, dftimewolf/lib/processors/grepper.py, dftimewolf/lib/processors/localplaso.py, dftimewolf/lib/processors/turbinia.py, dftimewolf/lib/state.py, tests/lib/collectors/filesystem.py, tests/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hunt.py, tests/lib/exporters/local_filesystem.py, tests/lib/processors/grepper.py, tests/lib/processors/turbinia.py, tests/lib/state.py, tests/test_modules/modules.py
* Changed name of process method to follow log2timeline style guide https://github.com/log2timeline/dftimewolf/issues/176
* Removed unnecessary returns in process method
=>  Renamed module process method and removed unnecessary returns #176

dftimewolf/lib/collectors/filesystem.py, dftimewolf/lib/collectors/gcloud.py, dftimewolf/lib/collectors/grr_base.py, dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, dftimewolf/lib/collectors/stackdriver.py, dftimewolf/lib/exporters/local_filesystem.py, dftimewolf/lib/exporters/timesketch.py, dftimewolf/lib/module.py, dftimewolf/lib/processors/grepper.py, dftimewolf/lib/processors/localplaso.py, dftimewolf/lib/processors/turbinia.py, dftimewolf/lib/state.py, docs/architecture.md, tests/lib/collectors/filesystem.py, tests/lib/collectors/grr_base.py, tests/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hunt.py, tests/lib/exporters/local_filesystem.py, tests/lib/processors/grepper.py, tests/lib/processors/turbinia.py, tests/lib/state.py, tests/test_modules/modules.py
* Changed name of setup method to follow log2timeline style guide https://github.com/log2timeline/dftimewolf/issues/176
=>  Renamed module setup method #176

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/collectors/grr_base.py, dftimewolf/lib/collectors/stackdriver.py, dftimewolf/lib/containers/interface.py, dftimewolf/lib/exporters/local_filesystem.py, dftimewolf/lib/exporters/timesketch.py, tests/lib/containers/interface.py, tests/lib/containers/report.py, tests/lib/containers/threat_intelligence.py
* removed several unused attribute container functions
* changes to docstrings
* renamed methods to match log2timeline style guide
=> Changes to use log2timeline style guide and removed unused methods #176

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/config.py, dftimewolf/lib/errors.py
Added BadConfigurationError exception and clean up
=> Added BadConfigurationError exception and clean up #157

dftimewolf/lib/processors/turbinia.py
Note that this is dependent on https://github.com/google/turbinia/pull/415 being submitted.
=> Validate evidence prior to making request

config/linux/jenkins_dftimewolf_install.sh, requirements.txt
Use `pip3` everywhere and install from Turbinia's HEAD instead of my own fork.
=> Jenkins install changes

dftimewolf/lib/collectors/gcloud.py, tests/lib/collectors/gcloud.py
This CL extracts picking of which disk names to copy to a function, so that we can override it if needed.
=> Extract disk name picking to a function

data/recipes/gcp_turbinia_disk_copy_ts.json
This was literally a comment :D https://github.com/tomchop/dftimewolf/blob/91bc247be85a2f3915a64ba1d8cf5ef322f5c382/dftimewolf/cli/recipes/gcp_turbinia_import.py#L39
=> remove comment that is not a comment

dftimewolf/lib/collectors/gcloud.py, dftimewolf/lib/containers/containers.py
* Add a generic `TicketAttribute` container to be used against ticketing systems
* Have the `GoogleCloudCollector` module store a `TicketAttribute` container with the generated analysis VM information
=> Add TicketAttribute container

dftimewolf/lib/processors/turbinia.py, tests/lib/processors/turbinia.py
Also add `BinaryExtractorTask.tar.gz` and `hashes.json` to the list of files that will be downloaded. This will be useful when the following PRs are merged
https://github.com/log2timeline/plaso/pull/2744
https://github.com/google/turbinia/pull/448
=> Refactor Turbinia processor

dftimewolf/lib/containers/containers.py, dftimewolf/lib/processors/turbinia.py, tests/lib/containers/containers.py, tests/lib/processors/turbinia.py
Have the Turbinia module store ThreatIntelligence containers that can be later used by other modules.
=> Turbinia module generates intel

tests/lib/collectors/gcloud_e2e.py
This allows e2e test from the CLI and gives the possibility to clean up the created VMs afterwards by calling the module's `CleanUp` method directly.
=> Add public CleanUp method in gcloud_e2e test.

config/linux/jenkins_dftimewolf_install.sh
=> Update jenkins script to py3

dftimewolf/lib/collectors/gcloud.py, requirements.txt, tests/lib/collectors/gcloud_e2e.py
=> Migrate from oauth2client to google.auth and update lilbcloudforensics dependency

dftimewolf/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hosts.py
Collector to pull timelines in bodyfile (or raw) format from GRR
=> GRRTimelineCollector

tests/lib/collectors/gcloud_e2e.py
=> Fix gcloud e2e test following libcloudforensics update

dftimewolf/lib/collectors/gcloud.py, dftimewolf/lib/exporters/gce_disk_export.py, requirements.txt, tests/lib/collectors/gcloud.py, tests/lib/collectors/gcloud_e2e.py, tests/lib/exporters/gce_disk_export.py
Marking this PR as draft until libcloudforensics's pip release is updated (until then Travis will bark).
=> Migrate from old to new libcloudforensics

requirements.txt, tests/lib/collectors/gcloud.py, tests/lib/collectors/gcloud_e2e.py, tests/lib/exporters/gce_disk_export.py
Following release `20200609`, update consumer methods.
=> Update libcloudforensics dependency and imports

setup.py, tests/lib/collectors/gcloud_e2e.py
- Fix gcloud e2e tests following the new release of libcloudforensics
- Fix Travis build (pylinting `setup.py`)
=> Fix gcloud e2e tests

dftimewolf/lib/exporters/timesketch.py, requirements.txt
Recent changes in TS changed the return object from analyzer run.
=> Changing TS exporter to reflect API changes

dftimewolf/lib/collectors/gcloud.py, tests/lib/collectors/gcloud.py
=> Move disk selection logic In gcloud.py to SetUp and fail early

tests/lib/collectors/aws.py
=> Add unit tests for AWS collector

data/recipes/gcp_logging_cloudsql_ts.json, dftimewolf/lib/processors/gcp_logging_timesketch.py, tests/lib/processors/gcp_logging_timesketch.py
Retrieves contents of log sink for current Cloud SQL instance types (MySQL, PostgreSQL and MSSQL) and additionally extracts log line severity.
=> CloudSQL Recipe

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/logging_utils.py, dftimewolf/lib/module.py, dftimewolf/lib/state.py
Add a RotatingFileHandler to the modules logger.
=> Better better logging

dftimewolf/lib/exporters/local_filesystem.py
Could also just as easily replace the elif with else, as makedirs would make any missing ones.
=> Make dftimewolf directory if non-existent.

dftimewolf/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hosts.py
* Enable querying hosts by client_id
* change some module-internal variable and function names
TODO: Change the variable names in recipes too.
=> Enable searching for GRR hosts by client ID

dftimewolf/lib/processors/localplaso.py, tests/lib/processors/localplaso.py
Will fail early with instructions on how to install.
Fixes #330
=> Check that log2timeline is present on system

dftimewolf/lib/exporters/scp_ex.py, dftimewolf/lib/preflights/ssh_multiplexer.py, tests/lib/exporters/scp_ex.py, tests/lib/preflights/ssh_multiplexer.py
* Host parameter is moved to after the SSH options
* Paths are grouped in SCP command (otherwise a new connection would be opened for every file)
* Other minor fixes
=> Fixes a few things in the SSH modules

dftimewolf/lib/exporters/timesketch.py
There is an extra `client` in one place.
=> Tiny bug fix in the TS exporter

data/recipes/upload_web_ts.json, dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/enhancers/timesketch.py, dftimewolf/lib/exporters/timesketch.py, requirements.txt
This PR updates the Timesketch exporter and enhancer modules according to updates upstream in the API client.
It also ups the requirements of the aPI client that is needed.
Additionally a new recipe is added that uses the TS enhancer, as well as to enable the TS enhancer as a module.
=> Making changes to the TS modules after an API update.

Pipfile, Pipfile.lock, config/linux/jenkins_dftimewolf_install.sh, requirements-dev.txt, requirements.txt, tests/lib/processors/turbinia_gcp.py
The turbinia dep is tracking my own fork that has an unpinned dependency for `google-cloud-logging`
=> Upgrade dependencies

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/state.py
* Be able to specify where to load recipes and config files using environment variables
* Display a verbose execution plan for the recipe
=> Control data dir and config files

dftimewolf/lib/collectors/gcp_logging.py, dftimewolf/lib/processors/gcp_logging_timesketch.py, tests/lib/processors/gcp_logging_timesketch.py
Better handling for quota limits and better preservation of some log information in retrieved logs.
=> Fix misc issues with GCP logging collector and processor

data/recipes/upload_turbinia.json, dftimewolf/lib/exporters/scp_ex.py, dftimewolf/lib/module.py, dftimewolf/lib/preflights/ssh_multiplexer.py, tests/lib/exporters/scp_ex.py, tests/lib/preflights/ssh_multiplexer.py
=> Tweaks in SSH multiplexer / exporter

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/collectors/aws_logging.py, dftimewolf/lib/collectors/azure.py, dftimewolf/lib/collectors/gcloud.py, dftimewolf/lib/collectors/gcp_logging.py, dftimewolf/lib/collectors/grr_base.py, dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, dftimewolf/lib/collectors/workspace_audit.py, dftimewolf/lib/exporters/gce_disk_export.py, dftimewolf/lib/exporters/local_filesystem.py, dftimewolf/lib/exporters/scp_ex.py, dftimewolf/lib/exporters/timesketch.py, dftimewolf/lib/logging_utils.py, dftimewolf/lib/module.py, dftimewolf/lib/processors/turbinia_artifact.py, dftimewolf/lib/processors/turbinia_gcp.py, mypy.ini
Logging "success" messages allows for module writers to highlight important messages in their modules such as successful download destinations, new timesketch sketch URLs, etc.
=> Add custom logging class to be able to log "success" messages

dftimewolf/lib/collectors/workspace_audit.py, dftimewolf/lib/containers/containers.py, dftimewolf/lib/processors/workspace_audit_timesketch.py, dftimewolf/lib/processors/workspace_format_strings.json
Adds a few more message strings, makes timesketch timeline names a bit nicer, and fixes some casing issues.
=> Fixes for workspace audit logs

dftimewolf/metawolf/metawolf.py
=> Metawolf: add `exit` command

dftimewolf/cli/dftimewolf_recipes.py
Makes import libs easier to read (and comment out if needed)
=> Fix import lines

dftimewolf/cli/dftimewolf_recipes.py
Closes #414
Otherwise, we're returnin 1 for errors and 0 for succesful execution, so all good.
=> exit(1) for Ctrl+C

.github/workflows/docs-publish.yaml, .github/workflows/docs.yaml
Actions will run with different GITHUB_TOKEN permissions
=> Separate doc publishing actions

dftimewolf/lib/containers/containers.py, dftimewolf/lib/processors/turbinia_gcp.py, tests/lib/processors/turbinia_gcp.py
* New YaraRule container
* Collect containers and add them to the Turbinia recipe called
=> Send YaraRule containers to Turbinia

dftimewolf/lib/collectors/workspace_audit.py, dftimewolf/lib/containers/containers.py, dftimewolf/lib/processors/workspace_audit_timesketch.py, tests/lib/processors/workspace_audit_timesketch.py
=> Improve handling of workspace logs with unknown types and Workspace log timeline names

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/logging_utils.py, dftimewolf/lib/module.py
It started as https://github.com/log2timeline/dftimewolf/pull/498, but this solution was simpler.
=> Each run logs in individual files

dftimewolf/lib/state.py, tests/lib/state.py, tests/test_modules/test_recipe.py, tests/test_modules/thread_aware_modules.py
Correction & tests for an edge case in container handling for ThreadAwareModules. 
Closes #503
=> Bugfix in TAM container handling

dftimewolf/lib/containers/containers.py, dftimewolf/lib/containers/interface.py, tests/lib/containers/containers.py, tests/lib/containers/interface.py
=> Move "attributes" attribute from Report to AttributeContainer

data/recipes/azure_logging_collect.json, dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/collectors/azure_logging.py, dftimewolf/lib/containers/containers.py, tests/lib/collectors/azure_logging.py
=> Create AzureLogsCollector module

dftimewolf/lib/collectors/aws_logging.py, tests/lib/collectors/aws_logging.py, tests/lib/collectors/azure_logging.py
=> Modify AWSLogsCollector to save logs in json-l

data/recipes/gcp_forensics.json, data/recipes/upload_turbinia.json, dftimewolf/lib/exporters/gce_disk_from_image.py, dftimewolf/lib/exporters/gcs_to_gce_image.py, dftimewolf/lib/module.py, dftimewolf/lib/processors/turbinia_base.py, dftimewolf/lib/processors/workspace_format_strings.json, docs/metawolf.md, docs/recipe-list.md, tests/cli/main_tool.py, tests/lib/collectors/aws_snapshot_s3_copy.py, tests/lib/collectors/aws_volume_snapshot.py, tests/lib/processors/turbinia_gcp.py
Did a run over the codebase to fix some typos
=> various typos fixed

dftimewolf/lib/collectors/osquery.py
Bug picked up during additional testing.
=> Fix NoneType error

dftimewolf/lib/processors/gcp_logging_timesketch.py, tests/lib/processors/gcp_logging_timesketch.py
=> GCPLoggingTimesketch set data_type gcp:log:json

dftimewolf/lib/module.py, tests/lib/collectors/grr_hosts.py
Closes #543
Also, a fix for a failing test.
=> Add Thread identifier to file log

dftimewolf/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hosts.py
As per [0], reverting a typo fix.
[0] https://github.com/log2timeline/dftimewolf/pull/551#pullrequestreview-901478252
=> Revert typo fix

dftimewolf/lib/collectors/aws_logging.py, dftimewolf/lib/collectors/azure_logging.py, dftimewolf/lib/containers/containers.py, tests/lib/collectors/aws_logging.py, tests/lib/collectors/azure_logging.py
=> Change AWSLogCollector and AzureLogCollector to output File containers

data/recipes/aws_logging_collect.json, dftimewolf/lib/collectors/aws_logging.py, tests/lib/collectors/aws_logging.py
=> Remove unused zone attribute from AWSLogsCollector

data/recipes/aws_logging_ts.json
=> Create aws_logging_ts recipe

data/recipes/azure_logging_ts.json
=> Create azure_logging_ts recipe

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/module.py
Too much logging removed in PR #551, reverting to try again.
=> Revert 551

dftimewolf/lib/exporters/gce_disk_export_dd.py
Nit: Missing space in the printed gcloud command
=> Fix printed gcloud command

.github/workflows/docs-publish.yaml, .github/workflows/docs.yaml, .github/workflows/install.yml, .github/workflows/mypy.yml, .github/workflows/pylint.yml, .github/workflows/unittests.yml, Pipfile, Pipfile.lock, requirements-dev.txt, requirements.txt
* Drop support for python 3.7
* Run tests / install on 3.9 / 3.10
=> Dependency bump

dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/exporters/s3_to_gcs.py, tests/test_modules/thread_aware_modules.py
=> Pylint fixes

dftimewolf/lib/processors/turbinia_base.py, dftimewolf/lib/processors/turbinia_gcp.py, tests/lib/processors/turbinia_gcp.py
Updates to type annotations for TurbiniaGCP modules.
=> Correct types for testing in Turbinia modules

.github/workflows/install.yml, docs/generate_recipe_doc.py
Hello, everyone in the community! 🙂
We have identified some errors in building and testing dftimewolf.
To resolve this error, we had to upgrade the version of pip and setuptools.
If there is no big problem, the check will be carried out normally.
If you have any additional comments or feedback, please leave a thread!
**Related Issue**
=> Fix: install dependencies error with pip and setuptools update.

config/linux/jenkins_dftimewolf_install.sh
* Also have the GRR install function sleep longer, as we've been getting "client not found" messages.
=> More verbose jenkins script

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/collectors/gce_disk_copy.py, dftimewolf/lib/containers/containers.py, dftimewolf/lib/exporters/gce_disk_from_image.py, dftimewolf/lib/exporters/gce_image_from_disk.py, dftimewolf/lib/exporters/gcs_to_gce_image.py, tests/lib/exporters/gce_disk_from_image.py, tests/lib/exporters/gce_image_from_disk.py, tests/lib/processors/gce_forensics_vm.py
Added in a module + tests that creates disk images from disks.
=> Added module GCEImageFromDisk

dftimewolf/cli/curses_display_manager.py, tests/cli/curses_display_manager.py
Created a curses display management class to handle displaying DFTW state via curses, rather than simply lines of log output. 
This is the first of 2 planned PRs, split up in the interests of PR size. This PR just creates the CursesDisplayManager class. A later PR will actually hook it up for usage.
=> Added in the CursesDisplayManager and tests

dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, tests/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hunt.py
=> Update file paths in GRRFileFinder[Flow|Hunt] using FSPath containers

dftimewolf/lib/containers/containers.py, dftimewolf/lib/containers/interface.py, dftimewolf/lib/enhancers/timesketch.py, tests/lib/containers/containers.py, tests/lib/containers/interface.py
=> Change AttributeContainer "attributes" to a Dict and rename

tests/test_modules/thread_aware_modules.py
Not sure how pytype/mypy/etc allowed this.....
=> Small type annotation fix

dftimewolf/cli/curses_display_manager.py, dftimewolf/cli/dftimewolf_recipes.py, tests/cli/curses_display_manager.py
=> Stream stderr to EnqueueMessage in curses mode

dftimewolf/lib/collectors/grr_hosts.py
The "ForensicArtifacts" repo has been gradually updated and a lot of the names have changed, updating the list in the GRR Artifact Collector class.
=> Updated default artifact names

dftimewolf/lib/processors/turbinia_base.py
refactor the TurbiniaProcess function, move the request polling logic to a new function and make it optional (default to True not break current clients).
=> refactor TurbiniaProcess method

dftimewolf/lib/containers/containers.py
These are used by the curses implementation.
=> Added __str__() overload to remaining containers

dftimewolf/lib/processors/turbinia_base.py
Need to download these for later processing (internally)
=> Collect Yara output files

tests/e2e/aws_disk_forensics.py
=> Fix for AWS->GCE E2E test

dftimewolf/lib/utils.py
=> Remove race condition on tar file creation in utils.py

dftimewolf/lib/processors/gcp_cloud_resource_tree.py, dftimewolf/lib/processors/gcp_cloud_resource_tree_helper.py, tests/lib/processors/test_data/resources_dict_dump.jsonl
The resource tree will now be exported to a DataFrame container. I also made lots of refactoring of the code.
=> Added export to DataFrame container to gcp_cloud_resource_tree and finished some refactoring of the same module

dftimewolf/cli/curses_display_manager.py, dftimewolf/lib/collectors/bigquery.py, tests/cli/curses_display_manager.py
Added a handler for signal.SIGWINCH (terminal resizing) that redraws the screen.
=> Added window resizing redraws to curses mode

docker/dev/Dockerfile, docker/dev/README.md, docker/dev/docker-compose.yaml, docker/dev/docker-entrypoint.sh, docs/developers-guide.md
This PR introduces a Dockerfile and docker-compose to be used for development.
=> Add dev instructions using Docker

dftimewolf/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hosts.py
* Raise real error when GRR returns an error
* Deal with crashed flows
* Allow fetching of children flows
=> Bugfixes / improvements in grr_hosts

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/errors.py, dftimewolf/lib/recipes/manager.py, dftimewolf/lib/resources.py, dftimewolf/lib/state.py, dftimewolf/lib/utils.py, dftimewolf/metawolf/metawolf.py, dftimewolf/metawolf/utils.py, tests/lib/recipes/manager.py, tests/lib/resources.py, tests/metawolf/utils.py
Adjusted argument parsing from recipes to use a new dataclass. Change is transparent to a user, but is prep work for #702
=> Adjusted recipe argument parsing

data/recipes/aws_disk_to_gcp.json, data/recipes/aws_logging_collect.json, data/recipes/aws_logging_ts.json, dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/collectors/aws_logging.py, tests/lib/collectors/aws_logging.py
Fixes #709, Fixes #710
Also removed unnecessary args from aws_disk_to_gcp recipe.
=> Add region to AWSLogsCollector

data/recipes/gcp_logging_gce_ts.json, dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/args_validator.py, dftimewolf/lib/utils.py, tests/lib/args_validator.py
Added an argument validator for dates + times. 
Also, added in parameter substitution into the `args.format` section of a recipe, so arguments can be compared, as this new DatetimeValidator does.
=> Added a datetime args validator

data/recipes/aws_forensics.json, data/recipes/aws_logging_collect.json, data/recipes/aws_logging_ts.json, data/recipes/aws_turbinia_ts.json, data/recipes/bigquery_collect.json, data/recipes/bigquery_ts.json, data/recipes/gce_disk_copy.json, data/recipes/grr_flow_collect.json, data/recipes/grr_timeline_ts.json, data/recipes/upload_turbinia.json, dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/args_validator.py, tests/cli/main_tool.py, tests/lib/args_validator.py
Added 3 more argument validators:
* FQDNValidator
* GRRHostValidator
* URLValidator
=> Added more Args validators

dftimewolf/lib/collectors/workspace_audit.py, tests/lib/collectors/workspace_audit.py
Provide what the date was 180 days ago so I don't have to calculate it each time
Update the test to match.
=> Provide maximum date & fix tests

dftimewolf/lib/collectors/grr_hosts.py
More durable for changes in the grr library when flows aren't found.
=> Broadened grr error catching in GrrFlowCollector

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/collectors/gce_disk_copy.py, dftimewolf/lib/collectors/gsheets.py, dftimewolf/lib/state.py
* Add the ability to manually pass a UUID to the dfTimewolf tool (useful when imported as a lib)
* Account for parameters passed as lists in dftimewolf/lib/collectors/gce_disk_copy.py (if invoked programmatically and not from the CLI)
* Fix a typing issue
=> Improvements

dftimewolf/lib/processors/turbinia_base.py, tests/lib/processors/turbinia_base.py
Refactor the Turbinia module authentication methods so we can easily refresh credentials and generate a new client object with valid tokens.
Fixes #769
=> TurbiniaProcessorBase: Refactor authentication logic and client creation

dftimewolf/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hosts.py
Remove deprecated GRR KeepAlive attribute.
=> Remove deprecated GRR flow

dftimewolf/lib/processors/turbinia_base.py, tests/lib/processors/turbinia_base.py
Edits to match Google's Python style guide.
Fixes an incorrect import in turbinia_base unit tests
=> Coding style edits

.github/workflows/unittests.yml, dftimewolf/lib/collectors/gce_disk_copy.py, dftimewolf/lib/processors/turbinia_base.py, dftimewolf/lib/state.py
Adjust typing checks that I missed in #780 to be python 3.9 compatible.
=> update typing checks

dftimewolf/lib/collectors/grr_hunt.py, tests/lib/collectors/grr_hunt.py
=> Fix GRRHuntYaraScanner test

dftimewolf/lib/processors/turbinia_base.py, dftimewolf/lib/processors/turbinia_gcp.py, tests/lib/processors/turbinia_base.py
Updates Turbinia modules for API changes
=> Updates to Turbinia modules

dftimewolf/lib/logging_utils.py
Only Santa should be checking it twice.
=> Do not format twice

dftimewolf/lib/processors/turbinia_gcp.py
This functionality was lost in a previous CL
See bug 315206831
=> Put Fraken results into a DataFrame container

dftimewolf/lib/collectors/grr_hosts.py
`CollectBrowserHistory` flow's payload are structured slightly differently than ArtifactCollectorFlow payloads or TimelineFlow payloads, so we account for that here to process files.
=> Account for payload provided by CollectBrowserHistory

config/e2e/jenkins_dftimewolf_install.sh
=> Small fix to E2E script

dftimewolf/cli/dftimewolf_recipes.py, dftimewolf/lib/args_validator.py, dftimewolf/lib/containers/containers.py, dftimewolf/lib/errors.py, dftimewolf/lib/recipes/manager.py, dftimewolf/lib/resources.py, docs/generate_recipe_doc.py, pytype.conf, tests/cli/main_tool.py, tests/lib/args_validator.py, tests/lib/recipes/manager.py, tests/lib/resources.py, tests/metawolf/utils.py
Apologies for the size of the change.
This is prepatory to changing the datetime validator to create datetime objects for modules to use
=> Updated validation code to support validators changing aguments

data/recipes/upload_turbinia.json, dftimewolf/lib/processors/turbinia_artifact.py, dftimewolf/lib/processors/turbinia_base.py
This pull requests makes it possible to upload forensic artifacts to Turbinia using the API server functionality.
=> Add support for file uploads using Turbinia API

dftimewolf/lib/collectors/grr_hosts.py, dftimewolf/lib/collectors/grr_hunt.py, dftimewolf/lib/collectors/osquery.py, tests/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hunt.py, tests/lib/collectors/osquery.py
=> Add check for trailing semicolon to osquery query value

dftimewolf/lib/collectors/gcp_logging.py
=> Fix GCPLogsCollector paging issue

dftimewolf/lib/utils.py
Reverts log2timeline/dftimewolf#923
=> Revert "Updated date interpolation into recipes"

data/recipes/gcp_logging_ts.json, dftimewolf/lib/processors/gcp_logging_timesketch.py, tests/lib/processors/gcp_logging_timesketch.py
Fixed the processor `gcp_logging_timesketch` and updated the recipe `gcp_logging_ts` to use the processor - `gcp_logging_ts` did not use any processor.
=> Fixed the recipe gcp_logging_ts and processor gcp_logging_timesketch

dftimewolf/lib/exporters/df_to_filesystem.py, dftimewolf/lib/processors/gcp_logging_timesketch.py
Also, small bugfix in gcp_logging_timesketch
=> Small cleanup in Dataframe -> FS exporter

dftimewolf/lib/collectors/grr_hosts.py, tests/lib/collectors/grr_hosts.py
This PR adds a standalone, blocking function that will request and wait for approval to a GRR client.
=> Add GRR approval function

data/recipes/gce_disk_copy.json, data/recipes/gce_disk_export.json
Allow project names with "." and ":" characters.
=> Update regex validator

dftimewolf/lib/processors/llm_base.py, dftimewolf/lib/processors/llmproviders/gemini.py, dftimewolf/lib/processors/llmproviders/interface.py, dftimewolf/lib/processors/llmproviders/manager.py, dftimewolf/metawolf/utils.py, tests/lib/processors/llmproviders/manager.py
Applies some corrections to documentation and pytype/pylint issues that were surfaced during a code import.
=> Fix typos and documentation

data/config.json, dftimewolf/lib/processors/llmproviders/__init__.py, dftimewolf/lib/processors/llmproviders/ollama.py, dftimewolf/lib/processors/llmproviders/vertex_ai.py, tests/lib/processors/llm_base.py, tests/lib/processors/llmproviders/ollama.py, tests/lib/processors/llmproviders/vertex_ai.py
Adds:
* a VertexAI provider module
* a Ollama provider module
Note: in the interest of PR size, these changes were split from https://github.com/log2timeline/dftimewolf/pull/944.
=> Add Ollama/VertexAI LLM Provider modules

dftimewolf/lib/processors/openrelik.py, tests/lib/processors/openrelik.py
Updates status to the correct failure state.
=> Chnages to OpenRelik module

dftimewolf/lib/containers/manager.py, dftimewolf/lib/state.py, tests/lib/containers/manager.py
Correct an issue where the container manager popped incorrect containers; tests for same.
=> Container manager bugfix

dftimewolf/cli/dftimewolf_recipes.py
Update logging levels:
* The logger is `DEBUG`
* The file handler is `DEBUG`
* The stdout stream handler is `INFO`, unless the env var `DFTIMEWOLF_DEBUG=1`
=> Update log level configs

dftimewolf/lib/exporters/df_to_filesystem.py, tests/lib/exporters/df_to_filesystem.py
=> Update default path for df_to_filesystem exporter.

dftimewolf/lib/collectors/gce_disk_copy.py, tests/lib/collectors/gce_disk_copy.py
=> Update gce disk copy module to try all instances before a hard failure

dftimewolf/lib/collectors/grr_hosts.py
remove local attributes for default artifacts in grr_host
=> remove local attribute from default artifacts

dftimewolf/lib/validators/datetime_validator.py, dftimewolf/lib/validators/manager.py, tests/lib/validators/datetime_validator.py
Ensures we're as flexible with formats as we intend to be
=> Add extra unit test for datetime validation

dftimewolf/lib/module.py, dftimewolf/lib/state.py
Which should have been a part of #1009
=> Plumb the `for_self_only` option through to modules
